# Generated by Django 5.0.6 on 2024-07-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=300)),
                ('transmission', models.CharField(max_length=30)),
                ('fuel', models.CharField(max_length=20)),
                ('seats', models.TextField(max_length=30)),
                ('price', models.IntegerField()),
                ('p_image', models.ImageField(upload_to='images')),
                ('p_image2', models.ImageField(upload_to='images')),
                ('p_image3', models.ImageField(upload_to='images')),
            ],
        ),
    ]
