# Generated by Django 5.0.6 on 2024-07-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivewheelsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='p_image',
            new_name='pimage',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='p_image2',
            new_name='pimage2',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='p_image3',
            new_name='pimage3',
        ),
    ]
