# Generated by Django 5.0.6 on 2024-07-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewheelsapp', '0002_rename_p_image_car_pimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='pimage4',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='pimage',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='pimage2',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='pimage3',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
