# Generated by Django 5.0.6 on 2024-07-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewheelsapp', '0003_car_pimage4_alter_car_pimage_alter_car_pimage2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pimage',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='pimage2',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='pimage3',
            field=models.ImageField(upload_to='images'),
        ),
    ]
