# Generated by Django 5.0.6 on 2024-07-11 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivewheelsapp', '0004_alter_car_pimage_alter_car_pimage2_alter_car_pimage3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='pimage2',
        ),
        migrations.RemoveField(
            model_name='car',
            name='pimage3',
        ),
        migrations.RemoveField(
            model_name='car',
            name='pimage4',
        ),
    ]
