# Generated by Django 5.0.6 on 2024-07-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewheelsapp', '0005_remove_car_pimage2_remove_car_pimage3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='pimage',
        ),
        migrations.AddField(
            model_name='car',
            name='cimage',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='car',
            name='cimage2',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='car',
            name='cimage3',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='car',
            name='cimage4',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
