# Generated by Django 5.0.6 on 2024-07-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewheelsapp', '0006_remove_car_pimage_car_cimage_car_cimage2_car_cimage3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.AddField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is_Availabel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='cimage',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='cimage2',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='cimage3',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='cimage4',
            field=models.ImageField(upload_to='images'),
        ),
    ]
