# Generated by Django 5.0.6 on 2024-07-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewheelsapp', '0009_alter_car_fuel_alter_car_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[(1, 'Petrol'), (2, 'Diesel'), (3, 'CNG')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.TextField(choices=[(6, '5STR'), (7, '7STR')], max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[(4, 'Manual'), (5, 'Automatic')], max_length=30),
        ),
    ]
