# Generated by Django 5.0.6 on 2024-07-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewheelsapp', '0010_alter_car_fuel_alter_car_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.TextField(choices=[(1, '5STR'), (2, '7STR')], max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[(1, 'Manual'), (2, 'Automatic')], max_length=30),
        ),
    ]
