# Generated by Django 5.0.6 on 2024-07-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewheelsapp', '0011_alter_car_seats_alter_car_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.IntegerField(choices=[(1, 'Petrol'), (2, 'Diesel'), (3, 'CNG')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.IntegerField(choices=[(1, '5STR'), (2, '7STR')], max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.IntegerField(choices=[(1, 'Manual'), (2, 'Automatic')], max_length=30),
        ),
    ]
