# Generated by Django 5.0.6 on 2024-07-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewheelsapp', '0013_alter_car_fuel_alter_car_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.IntegerField(choices=[(6, '5STR'), (7, '7STR')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.IntegerField(choices=[(4, 'Manual'), (5, 'Automatic')]),
        ),
    ]
