# Generated by Django 5.0.6 on 2024-07-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewheelsapp', '0014_alter_car_seats_alter_car_transmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('pnumber', models.CharField(max_length=12)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
