# Generated by Django 5.0.6 on 2024-07-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewheelsapp', '0015_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='loc',
            field=models.IntegerField(choices=[(8, 'pune'), (9, 'mumbai'), (10, 'hyderabad'), (11, 'chiplun'), (3, 'ratnagiri')], default=1),
        ),
    ]
