# Generated by Django 5.0.6 on 2024-07-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewheelsapp', '0016_car_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='caraddress',
            field=models.URLField(default=''),
        ),
    ]
