# Generated by Django 5.0.6 on 2024-07-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewheelsapp', '0017_car_caraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='loc',
            field=models.IntegerField(choices=[(8, 'pune'), (9, 'mumbai'), (10, 'hyderabad'), (11, 'chiplun'), (13, 'ratnagiri')], default=1),
        ),
    ]
