# Generated by Django 5.0.6 on 2024-07-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewheelsapp', '0020_bookingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='RC',
            field=models.CharField(default='', max_length=20),
        ),
    ]
