# Generated by Django 5.0.6 on 2024-07-14 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewheelsapp', '0021_car_rc'),
    ]

    operations = [
        migrations.CreateModel(
            name='totalrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickupDT', models.DateTimeField(auto_now_add=True)),
                ('dropoffDT', models.DateTimeField(default='%d-%m-%Y %H:%M')),
                ('Rid', models.ForeignKey(db_column='Rid', on_delete=django.db.models.deletion.CASCADE, to='drivewheelsapp.car')),
            ],
        ),
        migrations.DeleteModel(
            name='bookingcart',
        ),
    ]
