# Generated by Django 5.0.6 on 2024-07-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewheelsapp', '0023_alter_totalrent_dropoffdt_alter_totalrent_pickupdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalrent',
            name='pickupDT',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
