# Generated by Django 5.0.6 on 2024-07-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewheelsapp', '0024_alter_totalrent_pickupdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalrent',
            name='pickupDT',
            field=models.DateTimeField(),
        ),
    ]
