# Generated by Django 5.0.6 on 2024-07-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewheelsapp', '0026_customerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='cimage',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
