# Generated by Django 5.0.6 on 2024-07-16 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivewheelsapp', '0027_customerreview_cimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickupdate', models.DateTimeField()),
                ('hours', models.IntegerField(default=6)),
                ('car', models.ForeignKey(db_column='car', on_delete=django.db.models.deletion.CASCADE, to='drivewheelsapp.car')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='totalrent',
        ),
    ]
