# Generated by Django 5.0.6 on 2024-07-16 07:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivewheelsapp', '0028_booking_delete_totalrent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='carbooking',
        ),
    ]
